theme: minima
title: Angry Angler Blog
author: AngryRedAngler
email: your-email@domain.com
description: > # this means to ignore newlines until "baseurl:"
  The Angry Red Angler is really not very abgry at all. He is 
  a cute and sadly misunderstood little fish looking for friends.

# social links
twitter_username: your-twitter-handle # DO NOT include the @ character, or else the build will fail!
github_username:  your-github-handle # DO NOT include the @ character, or else the build will fail!

show_excerpts: true # set to false to remove excerpts on the homepage
